### ISSUE TITLE
Task 1.b User should be able to choose the reference panel

### ISSUE THREAD

**Issue by yocra3** [yocra3/epimutacions#2]
The current implementation uses a predefined control panel, which is explicitly defined inside the function. Instead, the function should contain the argument `reference`. This argument would contain a `GenomicRatioSet` with the data used as a reference. 

This issue should be solved together with #1. When `reference` is not defined, the function should use the remaining case samples as reference for epimutations discovery.

**Comment by jamesbaye** [comment]
Done as of #43 ?
